# Generated by Django 3.1.6 on 2021-02-17 20:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_name', models.CharField(
                    max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('name', models.CharField(max_length=50,
                                          primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('cur_status', models.CharField(
                    max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='FaultDetail',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_no', models.IntegerField()),
                ('fault_description', models.TextField(default='')),
                ('fault_date', models.DateField()),
                ('date_of_rectification', models.DateField(blank=True, default='')),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_report', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('department', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='complaints.department')),
                ('station', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='complaints.station')),
                ('status', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='complaints.status')),
            ],
        ),
    ]
